name: Release

on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        options: [major, minor, patch]
        required: true
        default: patch
        description: "The level of version bump to apply"

permissions:
  contents: read

env:
  DenoJson: "./deno.json"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          submodules: true

      - name: Check and Update Version
        id: update-version
        shell: pwsh
        run: |
          $PSNativeCommandUseErrorActionPreference = $true
          $ErrorActionPreference = 'Stop'

          # read $DenoJson
          $denoJsonPath = $env:DenoJson
          $json = Get-Content $denoJsonPath -Raw | ConvertFrom-Json
          $versionString = $json.version
          Write-Output "Current Module Version: $versionString"

          $ver = [System.Version]$versionString
          switch ('${{ github.event.inputs.bump-level }}') {
            'major' { $newVersion = "{0}.{1}.{2}" -f ($ver.Major + 1), 0, 0 }
            'minor' { $newVersion = "{0}.{1}.{2}" -f $ver.Major, ($ver.Minor + 1), 0 }
            'patch' { $newVersion = "{0}.{1}.{2}" -f $ver.Major, $ver.Minor, ($ver.Build + 1) }
            default { $newVersion = $versionString }
          }

          # write $DenoJson
          $json.version = $newVersion
          $json | ConvertTo-Json -Depth 10 | Set-Content $denoJsonPath -Encoding UTF8
          
          Write-Output "New Version: $newVersion"
          Write-Output "newVersion=$newVersion" | Tee-Object -FilePath ${env:GITHUB_OUTPUT} -Append

      - name: Commit and Push to Main
        shell: bash
        env:
          VERSION: ${{ steps.update-version.outputs.newVersion }}
        run: |
          git config user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git add "${DenoJson}"
          message="Update v${VERSION}"
          git commit -m "${message}"
          git push

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.5.4

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'          

      - name: Publish JSR & npm
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          deno install
          deno task publish

      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          publish: true
          commitish: main
          tag: v${{ steps.update-version.outputs.newVersion }}
          name: v${{ steps.update-version.outputs.newVersion }}
          version: ${{ steps.update-version.outputs.newVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}